#Create a file named application-local.properies
#This helps avoid conflicts with stuff that is different in our pc
#Your application-local.properties should have this properties which are different yet essential

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=