spring.application.name=Finylitics

spring.datasource.url=jdbc:postgresql://locahost:5432/finylitics
spring.datasource.password=Bivon@016
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect